theme = "toide" # catppuccin_mocha

[editor]
bufferline = "multiple"
line-number = "relative"
true-color = true
idle-timeout = 0 # instant completion
completion-trigger-len = 1
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-r = ":reload-all"
A-w = ":write"
L = ":buffer-next"
H = ":buffer-previous"

[keys.normal.backspace]
t = ":run-shell-command zellij action toggle-floating-panes"
g = ":run-shell-command zellij run -ic -- lazygit"
y = ":run-shell-command zellij run -ic -- yazi $PWD"
S = ":run-shell-command zellij run -ic -- serpl"
q = ":quit"
w = ":toggle whitespace.render all none"
r = ":toggle rulers [80,120] []"
s = ":toggle soft-wrap.enable"
d = ":toggle lsp.display-signature-help-docs"
h = ":toggle lsp.display-inlay-hints"
H = ":toggle file-picker.hidden"
n = ":toggle line-number relative absolute"
c = ":buffer-close"
C = ":buffer-close!"
b = ":sh git log -n 5 --format='format:%%h (%%an: %%ar) %%s' --no-patch -L%{cursor_line},+1:%{buffer_name}"
