[[language]]
name = "c"
formatter = { command = "clang-format"}

[[language]]
name = "cpp"
formatter = { command = "clang-format"}

[[language]]
name = "typst"
language-servers = ["tinymist"]

[language-server.tinymist]
command = "tinymist"
config = { preview.background.enabled = true, preview.background.args = ["--data-plane-host=127.0.0.1:0", "--invert-colors=never", "--open"], exportPdf = "onSave"}
